#!/usr/bin/env bash
set -e

SNOWSAW_DIR=".snowsaw"
SNOWSAW_BIN="bin/snowsaw"

SNOWBLOCKS_BASE_DIR_NAME="snowblocks"
SNOWROOT_BASE_DIR_NAME="snowroot"
SNOWBLOCKSDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$SNOWBLOCKS_BASE_DIR_NAME"
SNOWROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$SNOWROOT_BASE_DIR_NAME"

case "$1" in
  "root")
    sudo "${SNOWSAW_DIR}/${SNOWSAW_BIN}" -s "${SNOWROOTDIR}" "${@:2}"
    ;;
  "user")
    "${SNOWSAW_DIR}/${SNOWSAW_BIN}" -s "${SNOWBLOCKSDIR}" "${@:2}"
    ;;
  *)
    "${SNOWSAW_DIR}/${SNOWSAW_BIN}" -s "${SNOWBLOCKSDIR}" "${@:2}"
    sudo "${SNOWSAW_DIR}/${SNOWSAW_BIN}" -s "${SNOWROOTDIR}" "${@:2}"
    ;;
esac

