#!/usr/bin/env sh
pacman -Qent | awk '{print $1}' > other/pacman.txt
pacman -Qemt | awk '{print $1}' > other/yaourt.txt
code-insiders --list-extensions > other/code.txt
code-insiders --list-extensions > other/code-minimal.txt
