#! /bin/sh
bspc monitor -d web code model social game idle other

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc desktop ^1 -l monocle
bspc desktop ^2 -l monocle

bspc rule -a Vivaldi-stable -o desktop=^1
bspc rule -a "Code - Insiders" -o desktop=^2
bspc rule -a "jetbrains-idea-ce" -o desktop=^2
bspc rule -a "jetbrains-pycharm-ce" -o desktop=^2
bspc rule -a "NetBeans IDE 8.2" -o desktop=^2
bspc rule -a Blender -o desktop=^3
bspc rule -a discord -o desktop=^4
bspc rule -a Steam -o desktop=^5
bspc rule -a EVE -o desktop=^5
bspc rule -a Wine -o desktop=^6

bspc rule -a Steam state=floating
bspc rule -a Zenity state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Pinentry state=floating
bspc rule -a Xfce4-screenshooter state=floating
bspc rule -a Xfce4-notifyd-config state=floating

bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

bash ~/.bspwm/java_nonreparenting_wm_hack
polybar stat -r -c ~/.bspwm/config.ini &
polybar workspace -r -c ~/.bspwm/config.ini &
